core update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -30,7 +30,9 @@ if ! nix build --extra-experimental-features "nix-command flakes" --file core/se
   exit 1
 fi
 
-if ! nix run --experimental-features "nix-command flakes" .#dotlyx-setup "$@"; then
-  echo "❌ dotlyx-setup failed." >&2
-  exit 1
-fi
+# if ! nix run --experimental-features "nix-command flakes" .#dotlyx-setup "$@"; then
+#   echo "❌ dotlyx-setup failed." >&2
+#   exit 1
+# fi
+
+sudo ./result/bin/dotlyx-setup "$@"
